Homework-07 Lesson-9 - Task1/Task2 (Nazar_Buzyl)
viktor-beet-root/1-front-end pull request #106
Opened 2021-05-02 16:57 UTC by NazarBuzyl

2021-05-04 21:22 UTC, viktor-beet-root requested changes

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/README.md
> +Lesson09 - [Task 1](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework07-lesson-9/task-1/index.html) | [Task 2](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homew
Task 1 и Task 2 не соответствует макету

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-1/index.html
> +    <link rel="stylesheet" href="css/style.css">
сколько раз повторять порядок подключения

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-1/index.html
> +        <h2 class="blog_h2">Blog</h2>
blog-title

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-1/index.html
> +        <div class="blog-cards">
blog-list

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-1/index.html
> +            <div class="blog-card">
blog-item

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-1/index.html
> +                    <p class="blog-date"><span>20</span> nov</p>
не тянет на p лучше div

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-1/index.html
> +                    <p class="blog-description">Green Smoothies: Too Much of a Good Thing?</p>
а вот это походу заголовок был

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/README.md
> +Lesson09 - [Task 1](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework07-lesson-9/task-1/index.html) | [Task 2](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homew
![Снимок8](https://user-images.githubusercontent.com/73398559/117071449-d1d2ed00-ad37-11eb-9640-9a921a58166d.JPG)

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-2/index.html
> +                <figcaption>John Handson<span>Lead Designer</span></figcaption>
этот тег неправильно использован

2021-05-04 21:22 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-2/index.html
> +                    <a href="http://www.google.com">
это ссылка на внешний источник вспоминаем уроки

2021-05-07 21:19 UTC, viktor-beet-root requested changes

2021-05-07 21:19 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/README.md
> +Lesson09 - [Task 1](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework07-lesson-9/task-1/index.html) | [Task 2](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homew
Task 1 картинки экспортированы неправильно тень можно создать css

2021-05-14 21:51 UTC, viktor-beet-root requested changes

2021-05-14 21:51 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/README.md
> +Lesson09 - [Blog](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework07-lesson-9/task-1/index.html) | [WHO WE ARE](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/hom
Blog этой рамки не должно быть картинки экспортированы не верно http://joxi.ru/n2YQ8w3SeXXzG2

2021-05-14 21:51 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/README.md
> +Lesson09 - [Blog](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework07-lesson-9/task-1/index.html) | [WHO WE ARE](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/hom
WHO WE ARE не смущает ни че )) http://joxi.ru/DmBQX9OS499Lwr 
подключи perfect pisel и сравни с макетом

2021-05-14 21:51 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-1/index.html
> +        <h2 class="blog_h2">Blog</h2>
исправить все замечания

2021-05-28 19:13 UTC, viktor-beet-root requested changes

2021-05-28 19:13 UTC, viktor-beet-root commented on students/buzyl_nazar/homework07-lesson-9/task-1/css/style.css
> +    width: 370px;
у картинки не должно быть размера в пикселях как и у ее родителя 
картинка должна быть 100%, родитель 33,333%

2021-06-14 19:03 UTC, NazarBuzyl commented
не менял ничего, можете не смотреть.

2021-06-14 19:53 UTC, closed without merging