Kisilyova hw14 our team
viktor-beet-root/1-front-end pull request #144
Opened 2021-05-23 10:38 UTC by yuliyakisilyova

2021-05-28 19:24 UTC, viktor-beet-root requested changes

2021-05-28 19:24 UTC, viktor-beet-root commented on students/kisilyova_yuliya/homework14_our-team/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/homework14_our-team/build
текст на макете с лева, как у тебя справа http://joxi.ru/52aa1w7Ug90aM2
ни че не смущает)

2021-05-28 19:24 UTC, viktor-beet-root commented on students/kisilyova_yuliya/homework14_our-team/src/css/_fonts.scss
> +}
что-то забыла

2021-05-28 19:24 UTC, viktor-beet-root commented on students/kisilyova_yuliya/homework14_our-team/src/css/_header.scss
> +.container {
неожиданный файл для контейнера, через пол года ты вспомнишь что его в хедер положила

2021-05-28 19:25 UTC, viktor-beet-root requested changes

2021-05-28 19:25 UTC, viktor-beet-root commented on students/kisilyova_yuliya/homework14_our-team/src/index.html
> +                <div class="col-1"></div>
не пустых тегов тут не должно быть

2021-05-28 19:25 UTC, viktor-beet-root commented on students/kisilyova_yuliya/homework14_our-team/src/index.html
> +                <div class="col-1"></div>
удали все col-1 и пересчитай две колонки просто внутри там падинги укажи

2021-06-01 19:52 UTC, viktor-beet-root requested changes

2021-06-01 19:52 UTC, viktor-beet-root commented on students/kisilyova_yuliya/homework14_our-team/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/homework14_our-team/build
не исправлено! http://joxi.ru/52aa1w7Ug90aM2

2021-06-02 19:25 UTC, yuliyakisilyova commented on students/kisilyova_yuliya/homework14_our-team/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/homework14_our-team/build
исправила, а пейджес не пушнула) готово :)

2021-06-11 20:34 UTC, merged