Examination NazarBuzyl
viktor-beet-root/1-front-end pull request #171
Opened 2021-06-12 12:00 UTC by NazarBuzyl

2021-06-25 17:49 UTC, viktor-beet-root requested changes
а где ссылка на гитхабпэйджес

2021-06-25 19:25 UTC, viktor-beet-root requested changes

2021-06-25 19:25 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
http://joxi.ru/Q2KRnwNcywY4Vm не по макету

2021-06-25 19:25 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
http://joxi.ru/52aa1w7UgbM482 кнопка не помакету

2021-06-25 19:25 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
http://joxi.ru/p27n8JQcnWGKZm ни чего в глаза не бросается )

2021-06-25 19:25 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
http://joxi.ru/BA0LdxPtvP5MoA меню должно перекрывать экран не только вверху а везде

2021-06-25 19:25 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
http://joxi.ru/v29xQg6HRz8ZKm на мобиле уменьшить отступы

2021-06-25 19:25 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
http://joxi.ru/VrwBok4Hj817WA эти на мобиле стоят друг над другом

2021-07-11 21:21 UTC, viktor-beet-root requested changes

2021-07-11 21:21 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
http://joxi.ru/MAjy064t1dwY32 не по макету

2021-07-11 21:21 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
http://joxi.ru/VrwBok4HjowgEA упс

2021-07-25 17:01 UTC, viktor-beet-root requested changes

2021-07-25 17:01 UTC, viktor-beet-root commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
вообщем у тебя меню на мобиле рамдомно работает там что-то на js намутил

2021-07-25 17:33 UTC, NazarBuzyl commented on students/buzyl_nazar/examination_html-css/README.md
> +[Examination](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/examination_html-css/build/index.html)
у меня всё скролить, только что попробовал.

2021-07-28 12:10 UTC, merged