Homework-15 Lesson-25 - JavaSkript-3 (Nazar_Buzyl)
viktor-beet-root/1-front-end pull request #174
Opened 2021-06-15 11:17 UTC by NazarBuzyl

2021-06-18 20:48 UTC, viktor-beet-root requested changes

2021-06-18 20:48 UTC, viktor-beet-root commented on students/buzyl_nazar/homework15-lesson-25/src/js/script.js
> +    let num = firstNum * 100 + secondNum * 10 + thirdNum;
если бы еще что-то делал с этой переменной то она была бы нужно, а так можно сразу результат возвращать

2021-06-18 20:48 UTC, viktor-beet-root commented on students/buzyl_nazar/homework15-lesson-25/src/js/script.js
> +    if (width === undefined || width === undefined) area = length * length;
`width === undefined || width === undefined`
ширина или ширина  интересное сравнение

2021-06-18 20:48 UTC, viktor-beet-root commented on students/buzyl_nazar/homework15-lesson-25/src/js/script.js
> +        if (listPerfectNumber(i)) console.log(i);
в задаче сказано использовать функцию в который ты определяешь является ли число совершенным

2021-06-18 20:48 UTC, viktor-beet-root commented on students/buzyl_nazar/homework15-lesson-25/src/js/script.js
> +    result = h + ':' + m + ':' + s;
у тебя есть функция которая умеет выводить

2021-06-18 20:48 UTC, viktor-beet-root commented on students/buzyl_nazar/homework15-lesson-25/src/js/script.js
> +    let distinctionSeconds = Math.abs(sumSeconds1 - sumSeconds2);
Math.abs тут не нужен

2021-06-19 17:27 UTC, NazarBuzyl commented on students/buzyl_nazar/homework15-lesson-25/src/js/script.js
> +    if (width === undefined || width === undefined) area = length * length;
о да, дуже цікаво. Це новий просто метод.... ахах

2021-06-19 17:38 UTC, NazarBuzyl commented on students/buzyl_nazar/homework15-lesson-25/src/js/script.js
> +        if (listPerfectNumber(i)) console.log(i);
я решил просто ускорить процесс, поскольку совершенных чисел не так уж и много. То быстрее будет задать список этих чисел и проверять уже среди списка. Я знаю что нужно было использовать функцию проверки. Я предпочитаю ускорять процесс проверки, и оставлю у себя это решение.

2021-06-25 17:39 UTC, viktor-beet-root requested changes

2021-06-25 17:39 UTC, viktor-beet-root commented on students/buzyl_nazar/homework15-lesson-25/src/js/script.js
> +        if (listPerfectNumber(i)) console.log(i);
нет так не правильно ты должен найти совершенное число или нет

2021-07-11 21:15 UTC, merged