Kisilyova Yuliya first exam
viktor-beet-root/1-front-end pull request #183
Opened 2021-06-20 11:59 UTC by yuliyakisilyova

https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/first_exam/build

2021-06-25 17:46 UTC, viktor-beet-root requested changes

2021-06-25 17:46 UTC, viktor-beet-root commented on students/kisilyova_yuliya/first_exam/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/first_exam/build
http://joxi.ru/Drl8ad4cG0aNJr не по макету

2021-06-25 17:46 UTC, viktor-beet-root commented on students/kisilyova_yuliya/first_exam/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/first_exam/build
http://joxi.ru/Y2L3jwJHMQ0Zgm не влезли в экран)

2021-06-25 17:46 UTC, viktor-beet-root commented on students/kisilyova_yuliya/first_exam/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/first_exam/build
http://joxi.ru/4Ak73W4c0XO3gA неправильно выровнен текст

2021-06-25 17:46 UTC, viktor-beet-root commented on students/kisilyova_yuliya/first_exam/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/first_exam/build
http://joxi.ru/ZrJaVwlUbMEL4A и какие глаза нужно иметь чтобы это прочитать)

2021-07-11 21:26 UTC, viktor-beet-root requested changes

2021-07-11 21:26 UTC, viktor-beet-root commented on students/kisilyova_yuliya/first_exam/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/first_exam/build
к сожалению ссылка не работает презалей

2021-07-12 08:42 UTC, yuliyakisilyova commented on students/kisilyova_yuliya/first_exam/README.md
> +https://yuliyakisilyova.github.io/1-front-end/students/kisilyova_yuliya/first_exam/build
done

2021-07-25 16:23 UTC, merged