Examination - Monticello NazarBuzyl
viktor-beet-root/1-front-end pull request #200
Opened 2021-07-24 10:48 UTC by NazarBuzyl

2021-07-25 16:56 UTC, viktor-beet-root requested changes

2021-07-25 16:56 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
http://joxi.ru/Q2KRnwNcyXxlRm где слайдер на первом блоке

2021-07-25 16:56 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
меню должно появляться сверху после того как прокрутили 200 пикселей

2021-07-25 16:56 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
http://joxi.ru/l2Z5vwOfRkxvxm на макете там ховер есть

2021-07-25 16:56 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
нет валидации формы

2021-07-25 16:56 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
мобила http://joxi.ru/LmGLVw1tgboog2 уменьшить отступы

2021-07-25 16:56 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
http://joxi.ru/bmoqol4s7oPPkA

2021-07-25 16:56 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/src/js/slider.js
> +// })
проследи за последними строками 
комментированного кода не должно быть

2021-07-30 13:55 UTC, NazarBuzyl commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
всё исправил кажется

2021-08-04 17:03 UTC, viktor-beet-root requested changes

2021-08-04 17:03 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
эта форма все еще работает неправильно,
если нажать на кнопку с не заполненной формой происходит сабмит, а должно вывалиться сообщение что что-то пошло не так
http://joxi.ru/VrwBok4HjkP1zA

2021-08-08 09:33 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
меню работает не правильно)
1 главный блок
2 what we do
3 lates news
5 get in touch
когда доскролили или перешли по клику пункт должен под светиться точка стает белой

2021-08-08 09:33 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
фота если поле пусто или заполнено неправильно нужно об этом сообщить соответствующим сообщением

2021-08-11 19:49 UTC, NazarBuzyl commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
добавил функцию..

2021-08-14 08:18 UTC, viktor-beet-root requested changes

2021-08-14 08:18 UTC, viktor-beet-root commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
http://joxi.ru/J2bRew8cgobQw2 нет сообщений что поле не заполненно

2021-08-15 13:47 UTC, NazarBuzyl commented on students/buzyl_nazar/architecture/README.md
> +Examination - [Monticello | International group](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/architecture/build/index.html)
Виправив...

2021-08-16 20:41 UTC, merged