Homework-01 Lesson-1 - Resume
viktor-beet-root/1-front-end pull request #34
Opened 2021-04-16 19:32 UTC by NazarBuzyl

2021-04-18 20:51 UTC, viktor-beet-root commented on students/buzyl_nazar/homework01-resume/en_resume.html
> +                <span>C:</span><a href="tel:+380967741535">+38 096 774 15 35</a>
<span>C:</span> может все таки стронг) проверь все ниже

2021-04-18 20:51 UTC, viktor-beet-root commented on students/buzyl_nazar/homework01-resume/en_resume.html
> +            <div>
на див не тянет, а на абзац очень похоже

2021-04-19 15:15 UTC, NazarBuzyl commented on students/buzyl_nazar/homework01-resume/en_resume.html
> +                <span>C:</span><a href="tel:+380967741535">+38 096 774 15 35</a>
Можно....

2021-04-19 15:15 UTC, NazarBuzyl commented on students/buzyl_nazar/homework01-resume/en_resume.html
> +            <div>
Согласен!

2021-04-20 21:26 UTC, viktor-beet-root requested changes

2021-04-20 21:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework01-resume/en_resume.html
> +            <div>
ну если согласен нужно исправить))) тут и дальше везде

2021-04-21 06:59 UTC, NazarBuzyl commented on students/buzyl_nazar/homework01-resume/en_resume.html
> +            <div>
тепер здається все виправив

2021-04-23 20:17 UTC, viktor-beet-root requested changes

2021-04-23 20:17 UTC, viktor-beet-root commented on students/buzyl_nazar/homework01-resume/en_resume.html
> +        <p>
этот тег не нужен убрать везде подобное в р может быть только текст и строчные теги

2021-04-23 21:01 UTC, viktor-beet-root requested changes

2021-04-23 21:01 UTC, viktor-beet-root commented on students/buzyl_nazar/homework01-resume/index.html
> +        <p>
что-то пропустил

2021-04-23 21:01 UTC, viktor-beet-root commented on students/buzyl_nazar/homework01-resume/en_resume.html
> +        <p>
и тут

2021-04-23 21:12 UTC, NazarBuzyl commented on students/buzyl_nazar/homework01-resume/index.html
> +        <p>
в мене все эти дивы были в первой версии резюме, вы сказали "на див не тянет, а на абзац очень похоже". Вот я и поставил р ))
Так что нужно..

2021-04-25 20:16 UTC, merged