homework_les_2
viktor-beet-root/1-front-end pull request #35
Opened 2021-04-16 19:44 UTC by vadym-kindsfater

2021-04-17 18:29 UTC, viktor-beet-root requested changes

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2.html
> +    <title>Document</title>
title должен быть осмысленным

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2.html
> +<p align="center"><img src="/Users/user/Desktop/develop/ph1.png" width="100", height="130"></p>
картинка добавлена не верно что-то забыл
а валидатором проверить?
путь так же не верный

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2.html
> +    <li><b>tel: </b> +380 99 001 02 03 </li>
телефон должен быть ссылкой

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2.html
> +    <li><b>email: </b> random_mail@gmail.com </li>
эмаил должен быть ссылкой

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2.html
> +    <h3> Key strengths </h3>
где перекрестные ссылки на английскую версию

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2.html
> +           <p align="center"> <a href="/Users/user/Desktop/develop/1-front-end/students/kindsfater_vadym/homework_2/homework2_ua.html" title="welcome" target="_blank">ua_version</a> </p>
путь не верный не будет работать на сервере

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +    <title>Document</title>
так же и этот документ на укр языке

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +<html lang="en-uk">
что-то одно

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +<p align="center"><img src="/Users/user/Desktop/develop/ph1.png" width="100", height="130"></p>
путь не верный, картинка добавлена не верно 
валидатор!!

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +    <li><b>тел: </b> +380 99 001 02 03 </li>
то же что и англ.

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +    <h3> Бекграунд </h3>
перекрестные ссылки

2021-04-17 18:29 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +            <p align="center"><a href="/Users/user/Desktop/develop/1-front-end/students/kindsfater_vadym/homework_2/homework2.html" title="welcome" target="_blank">англійска версія</a></p>
путь

2021-04-23 20:51 UTC, viktor-beet-root requested changes

2021-04-23 20:51 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2.html
> +    <p align="center"><img src="/homework_2/img/ph1.png" width="100" , height="130" alt="boss"></p>
и это работает?? на гитхабе пробовал открывать?
валидатор не использовал((

2021-04-24 05:51 UTC, vadym-kindsfater commented
работает, по крайней мере в VS Code

пт, 23 апр. 2021 г. в 23:51, Viktor Dehtiarov ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In students/kindsfater_vadym/homework_2/homework2.html
> <https://github.com/viktor-beet-root/1-front-end/pull/35#discussion_r619488491>
> :
>
> > @@ -0,0 +1,44 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>CV</title>
>
> +</head>
>
> +
>
> +<body>
>
> +    <h1 align="center"> Vadym Kindsfater </h1>
>
> +    <p align="center"><img src="/homework_2/img/ph1.png" width="100" , height="130" alt="boss"></p>
>
>
> и это работает?? на гитхабе пробовал открывать?
> валидатор не использовал((
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/viktor-beet-root/1-front-end/pull/35#pullrequestreview-643654442>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATUU5XUQC4YPZ6ON6LE2PNLTKHMU3ANCNFSM43CDXEVQ>
> .
>

2021-04-25 20:31 UTC, viktor-beet-root requested changes

2021-04-25 20:31 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +    <p><img src="/homework_2/img/ph1.png" width="100" height="130" alt="boss"></p>
путь к картинке!!!

2021-04-25 20:31 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +    <h2 id="contacts_ua"><a href="/homework_2/homework2.html#gen_en"> Контакти </a></h2>
путь !!

2021-04-25 20:31 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +    <h2 id="background_ua"> <a href="/homework_2/homework2.html#key_en">Бекграунд </a> </h2>
путь

2021-04-25 20:31 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +        <p><a href="/homework_2/homework2.html" title="welcome" target="_blank">англійска версія</a></p>
путь

2021-04-25 20:31 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +    <h2 id="experience_ua"> <a href="/homework_2/homework2.html#exp_en"> Досвід </a></h2>
путь

2021-04-25 20:31 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2_ua.html
> +    <h2 id=education_ua> <a href="/homework_2/homework2.html#edu_en"> Освіта </a> </h2>
путь

2021-04-25 20:31 UTC, viktor-beet-root commented on students/kindsfater_vadym/homework_2/homework2.html
> +        <p> <a href="/homework_2/homework2_ua.html" title="welcome" target="_blank">ua_version</a> </p>
пути не правильные

2021-04-27 21:58 UTC, merged