Homework-02 Lesson-4 - List/Link
viktor-beet-root/1-front-end pull request #37
Opened 2021-04-16 20:05 UTC by NazarBuzyl

2021-04-18 20:52 UTC, viktor-beet-root requested changes

2021-04-18 20:52 UTC, viktor-beet-root commented on students/buzyl_nazar/homework02-lesson-4/task-1.html
> +                    <label> <input type="checkbox">Телятинна</label> <br>
привяжи лейблы тут по другому

2021-04-19 15:54 UTC, NazarBuzyl commented on students/buzyl_nazar/homework02-lesson-4/task-1.html
> +                    <label> <input type="checkbox">Телятинна</label> <br>
изменил. Надеюсь правильно понял замечание

2021-04-20 21:27 UTC, viktor-beet-root requested changes

2021-04-20 21:27 UTC, viktor-beet-root commented on students/buzyl_nazar/homework02-lesson-4/task-1.html
> +                    <input type="checkbox"><label>Курятина</label> <br>
лейблы не привязанны к чекбоксу нужно привязать желательно двумя способами

2021-04-23 20:19 UTC, viktor-beet-root requested changes

2021-04-23 20:19 UTC, viktor-beet-root commented on students/buzyl_nazar/homework02-lesson-4/task-1.html
> +                <li>
на само деле это не ul li это могли быть секшены или дивы даже

2021-04-23 20:19 UTC, viktor-beet-root commented on students/buzyl_nazar/homework02-lesson-4/task-2-02.html
> +    <article>
артикл был бы если бы было общее название а его нет

2021-04-23 20:31 UTC, NazarBuzyl commented on students/buzyl_nazar/homework02-lesson-4/task-2-02.html
> +    <article>
виправив, просто добавив заголовок..

2021-04-23 20:34 UTC, NazarBuzyl commented on students/buzyl_nazar/homework02-lesson-4/task-1.html
> +                <li>
да согласен, но в задание стояло правило, что нужно использовать ul или ol/ всё таки это списки должны были быть

2021-04-23 21:00 UTC, viktor-beet-root requested changes

2021-04-23 21:00 UTC, viktor-beet-root commented on students/buzyl_nazar/homework02-lesson-4/task-1.html
> +                <li>
тогда нужно правильно использовать ul li они не могут заменить секшены

2021-04-25 20:09 UTC, merged