Homework-03 Lesson-5 - Task1-simple (Nazar_Buzyl)
viktor-beet-root/1-front-end pull request #42
Opened 2021-04-17 12:58 UTC by NazarBuzyl

2021-04-18 20:58 UTC, viktor-beet-root requested changes

2021-04-18 20:58 UTC, viktor-beet-root commented on students/buzyl_nazar/homework03-task1-lesson-5/css/style.css
> +  width: 785px;
очень плохая идея
для бади никогда ширину не задаем

2021-04-18 20:58 UTC, viktor-beet-root commented on students/buzyl_nazar/homework03-task1-lesson-5/css/style.css
> +  margin-right: auto;
тоже самое

2021-04-18 20:58 UTC, viktor-beet-root commented on students/buzyl_nazar/homework03-task2-lesson-5/css/style.css
> +  margin-right: auto;
уже писал выше

2021-04-18 20:58 UTC, viktor-beet-root commented on students/buzyl_nazar/homework03-task1-lesson-5/css/style.css
> +body {
файлы css отформатированы не верно 
отступ должен быть 4 пробела тут 2

2021-04-18 20:58 UTC, viktor-beet-root commented on students/buzyl_nazar/homework03-task2-lesson-5/index.html
> +                <figure><img src="img/img03.jpg"><figcaption>Contact</figcaption></figure>
тег img задан не верно
ВАЛИДАТОР!!!!!

2021-04-19 15:55 UTC, NazarBuzyl commented on students/buzyl_nazar/homework03-task2-lesson-5/index.html
> +                <figure><img src="img/img03.jpg"><figcaption>Contact</figcaption></figure>
не заметил, наверное случайно удалил...

2021-04-20 21:38 UTC, viktor-beet-root requested changes

2021-04-20 21:38 UTC, viktor-beet-root commented on students/buzyl_nazar/homework03-task2-lesson-5/README.md
> +Lesson05 - [Your Company](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework03-task2-lesson-5/index.html)
ссылка не отрывается

2021-04-20 21:38 UTC, viktor-beet-root commented on students/buzyl_nazar/homework03-task1-lesson-5/README.md
> +Lesson05 - [My simple website](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework03-task1-lesson-5/index.html)
ссылка не отрывается

2021-04-23 20:52 UTC, viktor-beet-root requested changes

2021-04-23 20:52 UTC, viktor-beet-root commented on students/buzyl_nazar/homework03-task1-lesson-5/index.html
> +    <header>
хедер и футтер должны быть на ширину экрана

2021-04-23 21:03 UTC, merged