Home work Lesson1
viktor-beet-root/1-front-end pull request #49
Opened 2021-04-18 10:40 UTC by ilyavolovnik

2021-04-18 21:12 UTC, viktor-beet-root requested changes

2021-04-18 21:12 UTC, viktor-beet-root commented on students/index.html
> +<!DOCTYPE html>
этот файл не нужно было вообще трогать он не должен быть изменен

2021-04-18 21:12 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/en.html
> +                <h3>Work Experience</h3>
лишний отступ
отступы делаются только если есть вложенность тегов

2021-04-18 21:12 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/en.html
> +        <address>email:1231414@gmail.com</address>
это тег для почтового адреса, не элеронного 
email должен быть ссылкой

2021-04-18 21:12 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/en.html
> +        <address>phone:+3(33)331-11-11</address>
телефон должен быть ссылкой

2021-04-18 21:12 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/en.html
> +    <a href="https://www.facebook.com/ilya.volovnik/">facebook</a>
ссылки на внешние ресурсы что я про них говорил

2021-04-18 21:12 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/index.html
> +        <ul>
исправить форматирование писал выше

2021-04-18 21:12 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/index.html
> +        <address>phone:+3(33)331-11-11</address>
то же и англ.

2021-04-19 09:10 UTC, ilyavolovnik commented on students/index.html
> +<!DOCTYPE html>
Его удалить и создать новый index.html? или как лучше сделать?

2021-04-20 21:53 UTC, viktor-beet-root requested changes
Коммиты не должны быть на русском только латиница

2021-04-20 21:55 UTC, viktor-beet-root requested changes

2021-04-20 21:55 UTC, viktor-beet-root commented on students/index.html
> +<!DOCTYPE html>
вернуть в то состояние в котором он был)

2021-04-20 21:55 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/en.html
> +            <button><a href="./index.html" target="_blank">ru</a></button>
к кнопке ссылка не может лежать

2021-04-20 21:55 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/en.html
> +        <section>
я говорил про секшен 
24-25 строки удали
секшен это что-то большое не не только заглавие
переделай структуру

2021-04-20 21:55 UTC, viktor-beet-root commented on students/volovnik_ilya/lesson1/en.html
> +    <article>
где main

2021-06-18 20:05 UTC, closed without merging