anastasiya_chuprey_resume
viktor-beet-root/1-front-end pull request #50
Opened 2021-04-18 12:44 UTC by NastiaChooo

2021-04-18 21:14 UTC, viktor-beet-root requested changes

2021-04-18 21:14 UTC, viktor-beet-root commented on students/chuprey_anastasiya/home_work_1/index.html
> +    <p> <a href="/Users/anastasia/Desktop/MyCV/index_english.html"> English version</a></p>
путь не верный это не будет работать на сервере
попробуй открыть на своем гитхаб пейджес

2021-04-18 21:14 UTC, viktor-beet-root commented on students/chuprey_anastasiya/home_work_1/index.html
> +                    <li><a href="https://www.linkedin.com/in/anastasiya-chuprey-bb7a62209">linkedin</a></li>
ссылки на внешние ресурсы, я про них что-то говорил как они открываться должны

2021-04-18 21:14 UTC, viktor-beet-root commented on students/chuprey_anastasiya/home_work_1/index_eng.html
> +            <nav>
те же ошибки

2021-04-19 15:45 UTC, NastiaChooo reviewed
Added fixed files)

2021-04-19 16:36 UTC, closed without merging