Hw3 styles, 2 tasks, zhechkova alina
viktor-beet-root/1-front-end pull request #54
Opened 2021-04-19 10:52 UTC by alinazhechkova

2021-04-19 18:55 UTC, alinazhechkova commented
Я знаю, что нужно в файле readme, но он почему-то не отображается

https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw3/index.html

https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw3/task2.html

2021-04-20 21:52 UTC, viktor-beet-root requested changes

2021-04-20 21:52 UTC, viktor-beet-root commented on students/zhechkova_alina/hw3/index.html
> +            <div class="container">
этот див не имеет смысла

2021-04-20 21:52 UTC, viktor-beet-root commented on students/zhechkova_alina/hw3/index.html
> +                    <span class="strong_blue">odio</span>,
`<span class="strong_blue">odio</span>` это ссылки

2021-04-20 21:52 UTC, viktor-beet-root commented on students/zhechkova_alina/hw3/task2.html
> +                <a href="http://www.yourcompany.com" target="_blank"><img src="img/title.gif" alt="link"
это не картинка)

2021-04-20 21:52 UTC, viktor-beet-root commented on students/zhechkova_alina/hw3/task2.html
> +    <article>
где семантические теги?

2021-04-20 21:52 UTC, viktor-beet-root commented on students/zhechkova_alina/hw3/task2.html
> +            <div class="container">
уже писал

2021-04-20 21:52 UTC, viktor-beet-root commented on students/zhechkova_alina/hw3/index.html
> +    <article>
где header main?

2021-04-23 20:21 UTC, merged