Homework-04 Lesson-6 - Task1/Task2 (Nazar_Buzyl)
viktor-beet-root/1-front-end pull request #85
Opened 2021-04-23 20:13 UTC by NazarBuzyl

2021-04-23 20:57 UTC, viktor-beet-root requested changes

2021-04-23 20:57 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/README.md
> +Lesson06 - [Task 1](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework04-lesson-6/task1.html) | [Task 2](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework04-l
Task 1 не по макету

2021-04-23 20:57 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task2.css
> +* {padding: 0;
свойство с новой строки

2021-04-23 20:57 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task2.css
> +    height: 60px;
форматирование поправь

2021-04-23 20:57 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task2.css
> +    border-bottom: 3px solid #fff;
при ховере сипок не должне менять высоту

2021-04-25 20:26 UTC, viktor-beet-root requested changes

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    height: 50px;
высоту нельзя задавать

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    height: 63px;
если это круг то он должен  быть круглым а не овальным

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    margin: auto;
не имеет смысла

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    margin-bottom: 15px;
уже была попытка на 29 строке установить маржин

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    margin-bottom: 15px;
при ховере пишем только то что должно измениться

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    display: inline;
не имеет смысла

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    font: 14px;
не правильно использовал свойство

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    z-index: 18;
нет смысла

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    font-weight: regular;
не правильно

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +strong{
по тегу ничего не оформляем

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    height: 52px;
высота))

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    line-height: 1.429;
высота строки задается один раз для бади

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task1.css
> +    z-index: 21;
не имеет смысла

2021-04-25 20:26 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task2.css
> +	padding: 0;
не имеет смысла у тебя уже 2 строка есть

2021-04-27 21:55 UTC, viktor-beet-root requested changes

2021-04-27 21:55 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task2.css
> +}
а где белая рамка по кругу страницы?

2021-04-27 21:55 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task2.css
> +	padding: 0;
удали этот падинг 0

2021-04-27 21:55 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/css/style_task2.css
> +    border-bottom: 3px solid transparent;
форматирование поправь

2021-04-27 21:55 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/task2.html
> +    <link rel="shortcut icon" href="img/favicon.png" type="image/x-icon">
тип не тот

2021-05-04 20:33 UTC, NazarBuzyl commented on students/buzyl_nazar/homework04-lesson-6/README.md
> +Lesson06 - [Task 1](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework04-lesson-6/task1.html) | [Task 2](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework04-l
Здається все виправив...

2021-05-07 21:17 UTC, viktor-beet-root requested changes

2021-05-07 21:17 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/task2.html
> +    <link rel="shortcut icon" href="img/favicon.png" type="image/x-icon">
не исправлено атрибут type

2021-05-14 21:38 UTC, viktor-beet-root requested changes

2021-05-14 21:38 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/README.md
> +Lesson06 - [Task 1](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework04-lesson-6/task1.html) | [Task 2](https://nazarbuzyl.github.io/1-front-end/students/buzyl_nazar/homework04-l
Task 2 http://joxi.ru/gmv0Rx4H177WkA

2021-05-14 21:38 UTC, viktor-beet-root commented on students/buzyl_nazar/homework04-lesson-6/task2.html
> +    <link rel="shortcut icon" href="img/favicon.png" type="image/x-icon">
все еще не правильный атрибут у иконки погугли фавикот  в формате png

2021-05-28 19:16 UTC, merged