Hw5 box model zhechkova alina
viktor-beet-root/1-front-end pull request #92
Opened 2021-04-26 16:10 UTC by alinazhechkova

2021-05-02 19:13 UTC, viktor-beet-root requested changes

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/README.md
> +https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw5/
свг повреждены
сверстано не разу ни по макету

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/README.md
> +https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw5/task2
линии не должны двоиться при ховере 
![Снимок экрана 2021-05-02 213456](https://user-images.githubusercontent.com/73398559/116824445-f772c180-ab92-11eb-80f3-e404971ff396.png)

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/css/style.css
> +    content: 'Who we are';
интересно кто у кого копипастит? 
все надписи должны быть в html

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/css/style.css
> +h2 {
оформляем не по тегу а по классам

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/css/style.css
> +        0 2px 0 0 #ececec inset;
это не теть ) это должно была быть линия

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/css/style1.css
> +#bottom {
а это вообще не хорошо я говорил ни каких id

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/css/style1.css
> +h1 {
все теги убрать только классы

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/css/style1.css
> +*/
комментированных кусков кода не должно быть

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/index.html
> +                        <h3>Web <br> Development</h3>
без бр

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/task2.html
> +    <link rel="stylesheet" href="css/weather-icons-wind.min.css">
что-то тут перебор явно)))

2021-05-02 19:13 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/task2.html
> +    <div id="left"></div>
пустых тегов не должно быть

2021-05-03 05:41 UTC, alinazhechkova commented on students/zhechkova_alina/hw5/task2.html
> +    <div id="left"></div>
Это теги для создания рамки. Что там внутри должно быть?

2021-05-04 21:24 UTC, viktor-beet-root requested changes

2021-05-04 21:24 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/README.md
> +https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw5/
svg все еще не поломаны, посмотри у других студентов там есть нормальные

2021-05-04 21:24 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/README.md
> +https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw5/task2
не исправленно

2021-05-07 21:42 UTC, viktor-beet-root requested changes

2021-05-07 21:42 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/README.md
> +https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw5/
хорошо картинки норм, но теперь не по макуту

2021-05-07 21:42 UTC, viktor-beet-root requested changes

2021-05-07 21:42 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/README.md
> +https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw5/task2
тут стало хуже((

2021-05-16 17:18 UTC, viktor-beet-root requested changes

2021-05-16 17:18 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/css/style1.css
> +#bottom {
не исправленно

2021-05-16 17:18 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/task2.html
> +    <div id="left"></div>
не это не правильно))) рамку вокруг страницы можно намного проще сделать без лишних тегов

2021-05-28 19:36 UTC, viktor-beet-root requested changes

2021-05-28 19:36 UTC, viktor-beet-root commented on students/zhechkova_alina/hw5/README.md
> +https://alinazhechkova.github.io/1-front-end/students/zhechkova_alina/hw5/task2
что-то пошло не так http://joxi.ru/BA0LdxPtvlqRNA их должно быть видно нормально

2021-06-01 19:22 UTC, merged